### ISSUE TITLE
Add prefixes to Mount file

### ISSUE THREAD

**Issue by Sygmei** [ObEngine/ObEngine#349]
The Mount file currently looks like this : 

```yaml
Mount:
    Test: Workspace {
        path: "Test"
    }
    root: Path
```

We could add an optional prefix to some elements :
```yaml
Mount:
    Test: Workspace {
        path: "Test"
    }
    Fonts: Path {
        path: "Fonts",
        prefix: "fonts"
    }
    Icons: Path {
        path: "Sprites/Icons",
        prefix: "icons"
    }
    root: Path
```

or directly use the id as a prefix (which will give a prefix for all elements whether you want it or not) : 
```yaml
Mount:
    test: Workspace {
        path: "Test"
    }
    fonts: Path {
        path: "Fonts",
    }
    icons: Path {
        path: "Sprites/Icons",
    }
    root: Path
```

And then use the prefix in paths : 
```lua
local my_icon = Scene:createSprite("my_icon");
my_icon:loadFromFile("icons://heart_icon.png");
```

## Prefixes in prefixes

Ideally, we could use prefixes that references other prefixes, this is useful for Workspace subfolders for example : 

```yaml
Mount:
    test: Workspace {
        path: "Test"
    }
    test_sprites: Path {
        path: "test://Sprites",
    }
    root: Path
```

## `self://` prefix
We could also have a special prefix named `self://` which is a dynamic prefix using the local path of the current resource.

Some examples below :
- Animations could use the `self://` prefix to reference Sprites from the same folder as the Animation file.
- Animators could use the `self://` prefix to reference Animations from the same folder as the Animator file
- GameObjects could use the `self://` prefix to reference Scripts / Sprites from the same folder as the GameObject file
- Scenes could use the `self://` prefix to load resources from the same folder as the Scene file
