### ISSUE TITLE
Improve tree structure for GameObjects

### ISSUE THREAD

**Issue by Sygmei** [ObEngine/ObEngine#350]
Right now, ÖbEngine does have a lot of "static paths" where it expect to find a certain type of elements.

This issue will need to keep https://github.com/Sygmei/ObEngine/issues/183 in mind.

GameObjects have to follow the following tree structure
```
Data/
    GameObjects/
        GameObject1/
            GameObject1.obj.vili
            GameObject1.lua
        GameObject2/
            GameObject2.obj.vili
            GameObject2.png
```

### Resources paths

If you want to use a resource located in the same folder as the `GameObject**.obj.vili` file, you have to re-type the full path, making it annoying to type and harder to refactor / duplicate GameObjects.

We could use the `self://` feature from this [issue](https://github.com/Sygmei/ObEngine/issues/349) for long path problem mitigation).
Then you could reference scripts like that : 
```yaml
MyGameObject:
    Script:
        source: "self://GameObject.lua"
```

### Tree depth

Creating a GameObject involves a lot of subdirectories (`Data/GameObjects/GameObject1`).

Allowing the user to put GameObjects anywhere could be nice but introduces the problem of having to index your GameObjects somewhere if you want to use them by name.

This could be fixed by having to use GameObjects by path instead of by name and using the `prefix://` feature from this [issue](https://github.com/Sygmei/ObEngine/issues/349) as a best-practice in order to keep the paths shorts and clean.

For example, we could have something like this : 
`mount.vili`
```yaml
Mount:
    test: Workspace {
        path: "Test"
    }
    gameobjects: Path {
        path: "test://GameObjects
    }
    root: Path
```

And then use GameObjects like that : 
```my_scene.map.vili```
```yaml
GameObjects:
    my_game_object:
        type: "gameobjects://GameObject1
```

In order to improve the user experience, we could have a project bootstrapper which creates all those defaults folders and prefixes in the Mount path bringing both user-friendliness and flexibility (as you can specify your own prefixes / folders).

### GameObject naming

You have to be careful to properly re-use the same name for GameObject folder, GameObject filename and root object name in the `GameObject.obj.vili` making refactoring / copying GameObjects harder.

If we don't want to have a folder for each GameObject, we would have to reference a GameObject by its GameObject.obj.vili, making referencing less user-friendly and bothersome.

The name of the file could be standardized such as `object.obj.vili` for every GameObject but that makes file search / identification harder to use.

For the root object name, the problem is solved easily by simply removing it : 

`GameObject.obj.vili`
**Before**
```yaml
Test:
    Animator:
        path: "Sprites/Test"
    Script:
        source: "Data/GameObjects/Test/Test.lua"
```
**After**
```yaml
Animator:
    path: "Sprites/Test"
Script:
    source: "Data/GameObjects/Test/Test.lua"
```
